workflow:
  name: React Native Build

scripts:
  - name: Install Dependencies
    script: npm install

  - name: Build Android APK
    script: |
      cd android
      ./gradlew assembleRelease

publish:
  - artifact: app/build/outputs/apk/release/*.apk
